# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c072a36d896a7b0b07128b0fb38f1be96126c96ef12e90386c851ba4837734b8acc95c194d6066be798e2a077f252cbf658b2020dd0495c9519490407d3e728

test:
  secret_key_base: 9465e7ec071ead6b27d1e15ee213ec58dbd7008bb818c6987cbe1352a07c31bf64a29b82309a23efd68259d76ce91195cdae0d1e1e9e249b85397364a32f9982

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
